name: buildAndDeployWorker
on: 
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Install Dependencies"
        run: npm install
      - name: "Deploy Cloudflare"
        env: 
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npm run deploy
